name: CD Admin

on:
  push:
    paths:
      - 'admin/*'
      - 'admin/*/*'
      - 'admin/*/*/*'

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install
      run: (cd admin && npm install)

    - name: Build
      run: (cd admin && npm run build)
      env:
        REACT_APP_FIREBASE_APIKEY: ${{ secrets.FIREBASE_API_KEY }}
        REACT_APP_FIREBASE_AUTHDOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        REACT_APP_FIREBASE_DATABASEURL: ${{ secrets.FIREBASE_DATABASE_URL }}
        REACT_APP_FIREBASE_PROJECTID: ${{ secrets.FIREBASE_PROJECT_ID }}
        REACT_APP_FIREBASE_STORAGEBUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        REACT_APP_FIREBASE_MESSAGINGSENDERID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        REACT_APP_FIREBASE_APPID: ${{ secrets.FIREBASE_APP_ID_ADMIN }}

    - name: Deploy to Firebase
      run: (cd admin && npx firebase deploy --only hosting:saindev-ru-admin --token ${{ secrets.FIREBASE_TOKEN }})