name: CD Web

on:
  push:
    paths:
      - 'web/*'
      - 'web/*/*'
      - 'web/*/*/*'

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install
      run: (cd web && npm install)

    - name: Build
      run: (cd web && npm run build)
      env:
        GATSBY_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        GATSBY_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        GATSBY_FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        GATSBY_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        GATSBY_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        GATSBY_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        GATSBY_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID_WEB }}

    - name: Deploy to Firebase
      run: (cd web && npx firebase deploy --only hosting:saindev-ru --token ${{ secrets.FIREBASE_TOKEN }})